# Generated by Django 5.1.1 on 2024-09-25 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('tel', models.CharField(max_length=15)),
                ('nasc', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(blank=True, max_length=14, null=True)),
                ('grau_sint', models.CharField(choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho')], default='verde', max_length=30)),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=15)),
                ('tel', models.CharField(max_length=15)),
                ('ender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(blank=True, max_length=30, null=True)),
                ('peso_pet', models.FloatField(max_length=30)),
                ('idade_pet', models.CharField(blank=True, max_length=2, null=True)),
                ('raca_pet', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro'), ('aves', 'Aves')], default='gato', max_length=30)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Animal', to='home.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doutor', models.CharField(max_length=40)),
                ('crmv', models.CharField(max_length=30)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Veterinario', to='home.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loja', to='home.funcionario')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loja', to='home.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proced', models.CharField(default=True, max_length=30)),
                ('duracao', models.TimeField(blank=True, max_length=30, null=True)),
                ('grau_de_risco', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho')], default='verde', max_length=30, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.animal')),
                ('sintomas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consulta', to='home.sintomas')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_agend', models.CharField(blank=True, max_length=30, null=True)),
                ('data_agend', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.animal')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.consulta')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.veterinario')),
            ],
        ),
    ]
