# Generated by Django 5.1.1 on 2024-10-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='duracao',
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
    ]
